baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'RiRiSharp Hugo Template Site'
summaryLength = 40

[taxonomies]
	tag = "tags"
	author = "authors"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 20

[[menus.main]]
name = 'Authors'
pageRef = '/authors'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
