name = 'RiriSharpTheme'
license = 'MIT'
licenselink = 'https://github.com/RichardPoes/RiriSharpTheme/blob/main/LICENSE'
description = 'A bright minimalistic, responsive, color preference friendly theme.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/RichardPoes/RiriSharpTheme'

# If you have a running demo of the theme
demosite = 'https://theme.ririsharp.nl/'

# Taxonomy terms
tags = ['blog', 'math', 'dark']
features = ['dark theme', 'responsive', 'features', 'LaTeX', 'MathJax']

# If the theme has a single author
[author]
  name = 'RichardPoes'
  homepage = 'blog.ririsharp.nl'

# If porting an existing theme
[original]
  authors = [
  {name = "Patrick Kollitsch", homepage = "https://github.com/davidsneighbour"},
  {name = "Regis Philibert", homepage = "https://github.com/regisphilibert"},
  {name = "Bud Parr", homepage = "https://github.com/budparr"}
]
  homepage = 'https://github.com/theNewDynamic/gohugo-theme-ananke'
  repo = 'https://github.com/owner/repo'
